name: CI

on: [push, pull_request]

jobs:
  install_stable:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Test
        run: |
          set -e
          apt install llvm-dev libclang-dev clang
          apt install libiw-dev
          cargo build
          make check
        shell: bash
